---
docker_artifactory_name: 'artifactory' #check what this should be (web, app, db, etc)
docker_artifactory_image: 'docker.bintray.io/jfrog/artifactory-oss:5.4.6'
docker_artifactory_data_directory: /project/docker/artifactory
docker_artifactory_volumes:
  - '/project/docker/artifactory:/var/opt/jfrog/artifactory'
docker_artifactory_ports: '8888:8081'
docker_artifactory_env:
  DB_TYPE: 'postgresql'
  DB_HOST: 'localhost'
  DB_PORT: '5432'
  #The following must match the POSTGRE_USER and POSTGRES_PASSWORD values passed to PostgresSQL
  DB_USER: 'postgres'
  DB_PASSWORD: 'mysecretpassword'
  #Add extra Java options by uncommenting the following line
  #- EXTRA_JAVA_OPTIONS=Xmx4g