---
- name: Create Postgres data directories
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: root
    # Postgres runs as 'postgres' user in container
    mode: 0777
  with_items: '{{ docker_postgres_data_directories }}'
  tags:
    - docker_postgres

- name: Create a Postgres container
  docker_container:
    name: '{{ docker_postgres_name }}'
    image: '{{ docker_postgres_image }}'
    # restart: True
    hostname: '{{ docker_postgres_hostname }}'
    env: '{{ docker_postgres_env }}'
    published_ports: '{{ docker_postgres_ports }}'
    volumes: '{{ docker_postgres_volumes }}'
  tags:
    - docker_postgres
