---
ansible_user: 'vagrant'
# ansible_ssh_user: "{{ ansible_user }}"
become_user: "{{ ansible_user }}"

sudo_sudoers:
  # - 'ansible'
  # - 'jenkins'
  # - 'rundeck'
  # - 'sensu'
  - 'devops'

common_packages:
  - libselinux-python
  - selinux-policy
  - nano
  - net-tools
  - bind-utils
  - nc
  - screen
  - git
  - htop
  - ncdu
  - python-pip
  - haveged
  - rng-tools
  - unzip
  - wget
