---
- name: Create Jenkins data directories
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0777
  with_items: '{{ docker_jenkins_data_directories }}'
  tags:
    - docker_jenkins

- name: Create a Jenkins container
  docker_container:
    name: '{{ docker_jenkins_name }}'
    image: '{{ docker_jenkins_image }}'
    hostname: '{{ docker_jenkins_hostname }}'
    env: '{{ docker_jenkins_env }}'
    published_ports: '{{ docker_jenkins_ports }}'
    volumes: '{{ docker_jenkins_volumes }}'
  # notify: Restart Docker Jenkins
  tags:
    - docker_jenkins
