---
- name: Create Gitlab data directories
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: root
  with_items:
    - '/project/docker/gitlab/config'
    # - '/project/docker/gitlab/data'
    # - '/project/docker/gitlab/logs'
  tags:
    - docker_gitlab

- name: Configure Gitlab
  template:
    src: gitlab.rb.j2
    dest: /project/docker/gitlab/config/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart Docker Gitlab
  tags:
    - docker_gitlab

- name: Create a Gitlab container
  docker_container:
    name: '{{ docker_gitlab_name }}'
    image: 'gitlab/{{ docker_gitlab_image }}'
    # restart: True
    hostname: '{{ docker_gitlab_hostname }}'
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '{{ docker_gitlab_external_url }}'
    published_ports:
      - '80:80'
      - '2222:22'
    volumes:
      - '/project/docker/gitlab/config:/etc/gitlab'
      - '/project/docker/gitlab/logs:/var/log/gitlab'
      - '/project/docker/gitlab/data:/var/opt/gitlab'
  tags:
    - docker_gitlab
