---
- name: Create Gitlab data directories
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: root
  with_items: '{{ docker_gitlab_data_directories }}'
  tags:
    - docker_gitlab

- name: Configure Gitlab
  template:
    src: gitlab.rb.j2
    dest: /project/docker/gitlab/config/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart Docker Gitlab
  tags:
    - docker_gitlab

- name: Create a Gitlab container
  docker_container:
    name: '{{ docker_gitlab_name }}'
    image: '{{ docker_gitlab_image }}'
    # restart: True
    hostname: '{{ docker_gitlab_hostname }}'
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '{{ docker_gitlab_gitlab_external_url }}'
    published_ports: '{{ docker_gitlab_ports }}'
    volumes: '{{ docker_gitlab_volumes }}'
  tags:
    - docker_gitlab
