---
- name: Restart Docker Jenkins
  docker_container:
    name: '{{ docker_jenkins_name }}'
    image: '{{ docker_jenkins_image }}'
    hostname: '{{ docker_jenkins_hostname }}'
    env: '{{ docker_jenkins_env }}'
    published_ports: '{{ docker_jenkins_ports }}'
    volumes: '{{ docker_jenkins_volumes }}'
    state: started
    restart: True
