---
docker_registrator_name: 'registrator'
docker_registrator_image: 'gliderlabs/registrator:latest'
# Usage of /bin/registrator:
#   /bin/registrator [options] <registry URI>
#
#   -cleanup=false: Remove dangling services
#   -deregister="always": Deregister exited services "always" or "on-success"
#   -internal=false: Use internal ports instead of published ones
#   -ip="": IP for ports mapped to the host
#   -resync=0: Frequency with which services are resynchronized
#   -retry-attempts=0: Max retry attempts to establish a connection with the backend. Use -1 for infinite retries
#   -retry-interval=2000: Interval (in millisecond) between retry-attempts.
#   -tags="": Append tags for all registered services
#   -ttl=0: TTL for services (default is no expiry)
#   -ttl-refresh=0: Frequency with which service TTLs are refreshed
docker_registrator_command: 'consul://localhost:8500'
docker_registrator_volumes:
  - '/var/run/docker.sock:/tmp/docker.sock'
