---
docker_sonarqube_name: 'sonarqube'
docker_sonarqube_image: 'sonarqube:latest'
docker_sonarqube_hostname: 'localhost'
docker_sonarqube_env:
  SONARQUBE_JDBC_USERNAME: 'sonar'
  SONARQUBE_JDBC_PASSWORD: 'sonar'
  SONARQUBE_JDBC_URL: 'jdbc:postgresql://localhost/sonar'
docker_sonarqube_ports:
  - '9000:9000'
  - '9092:9092'
docker_sonarqube_volumes:
  - /project/docker/sonarqube/conf:/opt/sonarqube/conf
  - /project/docker/sonarqube/data:/opt/sonarqube/data
  - /project/docker/sonarqube/extensions:/opt/sonarqube/extensions
  - /project/docker/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  - /project/docker/sonarqube/temp:/opt/sonarqube/temp
docker_sonarqube_data_directories:
  - '/project/docker/sonarqube'

docker_sonarqube_ldap_host: "example.com"
#docker_sonarqube_ldap_port: "389"
#docker_sonarqube_ldap_uid: "sAMAccountName"
docker_sonarqube_ldap_bind_dn: "CN=Username,CN=Users,DC=example,DC=com"
docker_sonarqube_ldap_password: "password"
docker_sonarqube_ldap_base: "DC=example,DC=com"
