---
# must specify env when calling this playbook, which will limit the scope of the run
- name:  Verify env variable
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  tasks:
    - name: Check if env defined
      fail: msg="Variable 'env' must be defined."
      when: env is not defined
      tags: always
    - name: Targetted environment
      debug: var=env
      tags: always
    - name: Ansible user
      debug: var=ansible_user
      tags: always

### This play is for tasks which can be run after initial setup (e.g. Most tasks which use ansible sudoing)
## (e.g., ntp, syslog)
- name: Ansible Common Play
  hosts: "{{ env }}"
  become: True
  roles:
    - common
    - sshd
    - java

- include: HostType-consul-server.yml
- include: HostType-consul-agent.yml
- include: HostType-traefik-server.yml
