---
- name: Create a SonarQube container
  docker_container:
    name: '{{ docker_sonarqube_name }}'
    image: '{ docker_sonarqube_image }}'
    hostname: '{{ docker_sonarqube_hostname }}'
    published_ports: '{{ docker_sonarqube_ports }}'
    volumes: '{{ docker_sonarqube_volumes }}'
  tags:
    - docker_sonarqube
